
import { Jost } from 'next/font/google';
import "./globals.css";
import Layout from "@/components/Layout";

const jost = Jost({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jost.className}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
